//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Guest
    {


        public int GuestId { get; set; }

        public int RoomId { get; set; }

        public int TotalDays { get; set; }

        public int TotalPrice {get; set;}
        public string GuestName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string IdProofType { get; set; }
        public string IdProofNumber { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public bool Status { get; set; }
        public string IDProofPhoto { get; set; }

        public int RoomType { get; set; }

        public int NumberOfGuests { get; set; }



    }
}
